### ISSUE TITLE
setup.sh

### ISSUE THREAD

**Issue by jaroshevskii** [Talk-Is-Cheap-Give-Me-The-Code/cc-api#2]
Чому би для нього не використовувати python замість bash? На Python можна запросто реалізувати подібний скріпт, та й зрозуміти його буде простіше.

Начальну перевірку на Python 3, взагалі можна прибрати оскільки він і так перед установлений як кілька років на macOS/Linux

**Comment by tesla33io** [comment]
Якщо писати скрипти на python - це буде означати що увесь (або частка) процес преконфігурації системи буде залежати від python і на відміну від bash, немає гарантії що він  встановлений на усіх системах.

Та і чому б не використовувати bash? Це де-факто стандарт для unix скриптингу.

Не знаю чому я не подумав про це раніше, треба просто контейнерізувати цей проект, тоді буде можливість запускати його майже з будь-якої системи без проблем.

Якщо знаєш як працювати з Docker/docker-compose можеш зайнятися цим, інакше я зроблю це як буде час.

**Comment by jaroshevskii** [comment]
@jaroshevskii Було би цікаво Doker покликати, коли буде вільна хвилина займусь цим
